### ISSUE TITLE
Add New Translations

### ISSUE THREAD

**Issue by miyurusankalpa** [BeeIMG/languages#1]
Translate to other languages, base on file **[lang.en.php](https://github.com/BeeIMG/languages/blob/master/lang.en.php)**
see other files for examples. it's okay to leave the string as it is, if you don't know the word.
Please change to comment in the beginning of the file from English to language you are translating and update the README by adding the language to the list.

Thank you all for helping. When I posted this, we had only 3 translations and now we have more than 15, so I am going to list them, for ease of use and to avoid duplicates.
- [x] English
- [x] Sinhala
- [x] Russian by @pish4
- [x] Spanish by **Diego Cortez** & @jslirola
- [x] Belarusian by @p0v1n0m 
- [x] Traditional Chinese by **root**
- [x] Ukrainian by @pish4
- [x] Turkish  by @Om3rCitak 
- [x] Slovenian by @peterkokot 
- [x] Portuguese by @DailyMatters
- [x] Polish by @bSzala 
- [x] Dutch by @Martijnpold & @jerodev 
- [x] Italian by @daveismyname
- [x] Indonesian by @hndr91
- [x] French by @I-am-me
- [x] Croatian by @TheWildHorse 
- [x] Slovak by @Dasio & @Arthom & @pemrmaeoyve 
- [x] German by @dmaicher 
- [x] Hindi by @vaibhavbansal23
- [x] Brazilian Portuguese by @rafajaques
- [x] Catalan by @MNXANL
- [x] Czech by @StrnadRichard & @princezna
- [x] Norwegian by @RainoBoy97 
- [x] Tagalog by @norvinyecla 
- [x] Finnish by @mkainula
- [x] Swedish by @kajes
- [x] Malay by @od3n
- [x] Arabic by @stodar

**Comment by I-am-me** [comment]
I'm doing the French translation

**Comment by pish4** [comment]
I'll translate to ukrainian.

**Comment by bSzala** [comment]
I'm doing the Polish translation

**Comment by DailyMatters** [comment]
Going for a portuguese translation.

**Comment by hndr91** [comment]
I take Indonesian translation please

**Comment by hndr91** [comment]
@miyurusankalpa Can I ask something ? What is the context of "our home" menu ?

**Comment by Om3rCitak** [comment]
#10

**Comment by miyurusankalpa** [comment]
@hndr91 it refers to the homepage. it is used as a title, so its only visible on hover.

**Comment by hndr91** [comment]
adding Bahasa Indonesia #13

**Comment by MilindaLaknath** [comment]
Hi @miyurusankalpa,
 
I'm Milinda. I can translate it into Sinhala.

Thank you

**Comment by wahbigbig** [comment]
adding Traditional Chinese

**Comment by dmaicher** [comment]
Adding German translations :wink:

**Comment by rafajaques** [comment]
May I add Brazilian Portuguese?

**Comment by miyurusankalpa** [comment]
@rafajaques sure go ahead, we get lot of visits from brazil. use **pt_br** in file name, as Brazilian Portuguese does have a ISO 639 code name yet.

**Comment by vaibhavbansal23** [comment]
Adding Hindi language :smile:

**Comment by MNXANL** [comment]
I can translate to catalan (Spoken in Catalonia, a region in Spain) :-)

**Comment by rafajaques** [comment]
Sent pull request for pt-br #23
