### ISSUE TITLE
Remove closing tag from language files

### ISSUE THREAD

**Issue by rafajaques** [BeeIMG/languages#24]
Hey! This is just a suggestion.
It's a good practice to omit closing tag in pure-php files.
Sometimes IDEs may add blank spaces in the end of files and this may lead to header problems.
Anyway, just a suggestion.

**Comment by miyurusankalpa** [comment]
good point, I just researched on the topic and this seems like a good idea.

http://php.net/manual/en/language.basic-syntax.phptags.php
http://stackoverflow.com/a/4499749/1498958
